version: '3'

services:
  app-doc88:
    build: ./
    ports:
      - "3003:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network 

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "14306:3306"
    volumes:
     - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: doc88api
      MYSQL_ROOT_PASSWORD: 010203
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge


